version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: teebabs.oladejo74@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"

volumes:
  pgdata:
