databases:
  - name: property_service
    databaseName: property_service_production
    user: property_service

services:
  - type: web
    name: property_service
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: property_service
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
