---
openapi: 3.0.1
info:
  title: PROPERTIES API V1
  version: v1
paths:
  "/api/v1/properties":
    get:
      summary: list properties
      responses:
        '200':
          description: successful
    post:
      summary: create property
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                property_type:
                  type: string
                num_of_bedrooms:
                  type: integer
                num_of_sitting_rooms:
                  type: integer
                num_of_kitchens:
                  type: integer
                num_of_bathrooms:
                  type: integer
                num_of_toilets:
                  type: integer
                owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                valid_to:
                  type: string
              required:
              - address
              - property_type
              - num_of_bedrooms
              - num_of_sitting_rooms
              - num_of_kitchens
              - num_of_bathrooms
              - num_of_toilets
              - owner
              - description
              - valid_from
              - valid_to
  "/api/v1/properties/{id}":
    parameters:
    - name: id
      in: path
      description: Property ID
      required: true
      schema:
        type: string
    get:
      summary: show property
      responses:
        '200':
          description: successful
    patch:
      summary: update property partially
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                num_of_bedrooms:
                  type: integer
                num_of_sitting_rooms:
                  type: integer
                num_of_kitchens:
                  type: integer
                num_of_bathrooms:
                  type: integer
                num_of_toilets:
                  type: integer
                valid_to:
                  type: string
              required:
              - description
              - num_of_bedrooms
              - num_of_sitting_rooms
              - num_of_kitchens
              - num_of_bathrooms
              - num_of_toilets
              - valid_to
    put:
      summary: update property completely
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                num_of_bedrooms:
                  type: integer
                num_of_sitting_rooms:
                  type: integer
                num_of_kitchens:
                  type: integer
                num_of_bathrooms:
                  type: integer
                num_of_toilets:
                  type: integer
                valid_to:
                  type: string
              required:
              - description
              - num_of_bedrooms
              - num_of_sitting_rooms
              - num_of_kitchens
              - num_of_bathrooms
              - num_of_toilets
              - valid_to
  "/api/v1/properties/owner/{owner}":
    parameters:
    - name: owner
      in: path
      description: owner
      required: true
      schema:
        type: string
    get:
      summary: owner property
      responses:
        '200':
          description: successful
  "/api/v1/properties/property_address/{property_address}":
    parameters:
    - name: property_address
      in: path
      description: property_address
      required: true
      schema:
        type: string
    get:
      summary: property_address property
      responses:
        '200':
          description: successful
  "/api/v1/properties/filter":
    parameters:
    - name: owner
      in: query
      description: Owner of the property
      schema:
        type: string
    - name: property_type
      in: query
      description: Type of the property
      schema:
        type: string
    - name: num_of_bedrooms
      in: query
      description: Number of bedrooms
      schema:
        type: integer
    - name: num_of_sitting_rooms
      in: query
      description: Number of sitting rooms
      schema:
        type: integer
    - name: num_of_kitchens
      in: query
      description: Number of kitchens
      schema:
        type: integer
    - name: num_of_bathrooms
      in: query
      description: Number of bathrooms
      schema:
        type: integer
    - name: num_of_toilets
      in: query
      description: Number of toilets
      schema:
        type: integer
    - name: valid_to
      in: query
      format: date
      description: Validity date of the property
      schema:
        type: string
    get:
      summary: filter property
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: property-service.onrender.com
